usiddi4Proj4: usiddi4Proj4b.o usiddi4Proj4c.o usiddi4Proj4a.c
	gcc usiddi4Proj4a.c usiddi4Proj4b.o usiddi4Proj4c.o -o usiddi4Proj4

usiddi4Proj4b.o: usiddi4Proj4b.c usiddi4Proj4.h
	gcc -c usiddi4Proj4b.c

usiddi4Proj4c.o: usiddi4Proj4c.c usiddi4Proj4.h
	gcc -c usiddi4Proj4c.c